#!/bin/bash

echo "PERAIAH:: HI VENKAT HOW ARE YOU"
echo "VENKAT:: HELLO PERAIAH I AM GOOD WHAT ABOU YOU"
echo "PERAIAH:: I AM GOOD THANKYOU VENKAT WHAT ARE YOU DOING"
echo "VENKAT:: I DONING WELL PERAIAH THANKYOU PERAIAH"