#!/bin/bash

NAME1="RUTURAJ"
NAME2="DHONI"

echo "$NAME1:: HI $NAME2 HOW ARE YOU"
echo "$NAME2:: HELLO $NAME1 I AM GOOD WHAT ABOU YOU"
echo "$NAME1:: I AM GOOD THANKYOU $NAME2 WHAT ARE YOU DOING"
echo "$NAME2:: I DONING WELL $NAME1 THANKYOU"