- name: display disk size using register
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: disk size
    ansible.builtin.command: df -h 
    register: disk_size

  - name: display disk size
    ansible.builtin.debug:
      msg: "disk usage size is {{ disk_size.stdout }}"