- name: creating handler example
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: creatin user
    ansible.builtin.file:
      path: /home/ec2-user/lsad/got
      state: touch
    notify: Add data

  handlers:
    - name: Add data
      ansible.builtin.lineinfile:
        path: /home/ec2-user/lsad/got
        line: "Hello Linux"
     