- name: user with creating aruguments 
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: user with aruguments
    ansible.builtin.user:
    name: rain
    state: present
    create_home: yes
    uid: 1011
    gid: 1035
    groups: wheel,peraiah
    append: yes
    shell: /bin/bash
    
